export const CHANGE_BACKGROUND_COLOR = "CHANGE_BACKGROUND_COLOR";
export const CHANGE_SIDE_BAR_COLOR = "CHANGE_SIDE_BAR_COLOR";
export const TOGGLE_SIDE_BAR = "TOGGLE_SIDE_BAR";
export const TOGGLE_FIXED_PLUGIN = "TOGGLE_FIXED_PLUGIN";
export const TOGGLE_SLOT_MACHINE_SIZE = "TOGGLE_SLOT_MACHINE_SIZE";

export const SLOT_MACHINE_START = "SLOT_MACHINE_START";
export const SLOT_MACHINE_TICKET = "SLOT_MACHINE_TICKET";
export const SLOT_MACHINE_STOP = "SLOT_MACHINE_STOP";
